namespace RezPls.Enums
{
    public enum Job : byte
    {
        Unknown       = 0,
        Gladiator     = 1,
        Pugilist      = 2,
        Marauder      = 3,
        Lancer        = 4,
        Archer        = 5,
        Conjurer      = 6,
        Thaumaturge   = 7,
        Carpenter     = 8,
        Blacksmith    = 9,
        Armorer       = 10,
        Goldsmith     = 11,
        Leatherworker = 12,
        Weaver        = 13,
        Alchemist     = 14,
        Culinarian    = 15,
        Miner         = 16,
        Botanist      = 17,
        Fisher        = 18,
        Paladin       = 19,
        Monk          = 20,
        Warrior       = 21,
        Dragoon       = 22,
        Bard          = 23,
        WhiteMage     = 24,
        BlackMage     = 25,
        Arcanist      = 26,
        Summoner      = 27,
        Scholar       = 28,
        Rogue         = 29,
        Ninja         = 30,
        Machinist     = 31,
        DarkKnight    = 32,
        Astrologian   = 33,
        Samurai       = 34,
        RedMage       = 35,
        BlueMage      = 36,
        Gunbreaker    = 37,
        Dancer        = 38,

        ADV = Unknown,
        GLD = Gladiator,
        PGL = Pugilist,
        MRD = Marauder,
        LNC = Lancer,
        ARC = Archer,
        CNJ = Conjurer,
        THM = Thaumaturge,
        CRP = Carpenter,
        BSM = Blacksmith,
        ARM = Armorer,
        GSM = Goldsmith,
        LTW = Leatherworker,
        WVR = Weaver,
        ALC = Alchemist,
        CUL = Culinarian,
        MIN = Miner,
        BOT = Botanist,
        FSH = Fisher,
        PLD = Paladin,
        MNK = Monk,
        WAR = Warrior,
        DRG = Dragoon,
        BRD = Bard,
        WHM = WhiteMage,
        BLM = BlackMage,
        ACN = Arcanist,
        SMN = Summoner,
        SCH = Scholar,
        ROG = Rogue,
        NIN = Ninja,
        MCH = Machinist,
        DRK = DarkKnight,
        AST = Astrologian,
        SAM = Samurai,
        RDM = RedMage,
        BLU = BlueMage,
        GNB = Gunbreaker,
        DNC = Dancer,
    }

    public static class JobExtensions
    {
        public static string FullName(this Job job)
        {
            return job switch
            {
                Job.Gladiator     => "GLD",
                Job.Pugilist      => "PGL",
                Job.Marauder      => "MRD",
                Job.Lancer        => "LNC",
                Job.Archer        => "ARC",
                Job.Conjurer      => "CNJ",
                Job.Thaumaturge   => "THM",
                Job.Carpenter     => "CRP",
                Job.Blacksmith    => "BSM",
                Job.Armorer       => "ARM",
                Job.Goldsmith     => "GSM",
                Job.Leatherworker => "LTW",
                Job.Weaver        => "WVR",
                Job.Alchemist     => "ALC",
                Job.Culinarian    => "CUL",
                Job.Miner         => "MIN",
                Job.Botanist      => "BOT",
                Job.Fisher        => "FSH",
                Job.Paladin       => "PLD",
                Job.Monk          => "MNK",
                Job.Warrior       => "WAR",
                Job.Dragoon       => "DRG",
                Job.Bard          => "BRD",
                Job.WhiteMage     => "WHM",
                Job.BlackMage     => "BLM",
                Job.Arcanist      => "ACN",
                Job.Summoner      => "SMN",
                Job.Scholar       => "SCH",
                Job.Rogue         => "ROG",
                Job.Ninja         => "NIN",
                Job.Machinist     => "MCH",
                Job.DarkKnight    => "DRK",
                Job.Astrologian   => "AST",
                Job.Samurai       => "SAM",
                Job.RedMage       => "RDM",
                Job.BlueMage      => "BLU",
                Job.Gunbreaker    => "GNB",
                Job.Dancer        => "DNC",
                _                 => "ADV",
            };
        }

        public static string Abbreviation(this Job job)
        {
            return job switch
            {
                Job.Gladiator     => "Gladiator",
                Job.Pugilist      => "Pugilist",
                Job.Marauder      => "Marauder",
                Job.Lancer        => "Lancer",
                Job.Archer        => "Archer",
                Job.Conjurer      => "Conjurer",
                Job.Thaumaturge   => "Thaumaturge",
                Job.Carpenter     => "Carpenter",
                Job.Blacksmith    => "Blacksmith",
                Job.Armorer       => "Armorer",
                Job.Goldsmith     => "Goldsmith",
                Job.Leatherworker => "Leatherworker",
                Job.Weaver        => "Weaver",
                Job.Alchemist     => "Alchemist",
                Job.Culinarian    => "Culinarian",
                Job.Miner         => "Miner",
                Job.Botanist      => "Botanist",
                Job.Fisher        => "Fisher",
                Job.Paladin       => "Paladin",
                Job.Monk          => "Monk",
                Job.Warrior       => "Warrior",
                Job.Dragoon       => "Dragoon",
                Job.Bard          => "Bard",
                Job.WhiteMage     => "White Mage",
                Job.BlackMage     => "Black Mage",
                Job.Arcanist      => "Arcanist",
                Job.Summoner      => "Summoner",
                Job.Scholar       => "Scholar",
                Job.Rogue         => "Rogue",
                Job.Ninja         => "Ninja",
                Job.Machinist     => "Machinist",
                Job.DarkKnight    => "Dark Knight",
                Job.Astrologian   => "Astrologian",
                Job.Samurai       => "Samurai",
                Job.RedMage       => "Red Mage",
                Job.BlueMage      => "Blue Mage",
                Job.Gunbreaker    => "Gunbreaker",
                Job.Dancer        => "Dancer",
                _                 => "Adventurer",
            };
        }

        public static bool CanRaise(this Job job)
        {
            return job switch
            {
                Job.Conjurer    => true,
                Job.WhiteMage   => true,
                Job.Arcanist    => true,
                Job.Summoner    => true,
                Job.Scholar     => true,
                Job.Astrologian => true,
                Job.RedMage     => true,
                Job.BlueMage    => true,
                _               => false,
            };
        }
    }
}